### ISSUE TITLE
اشکال در راه اندازی frontend

### ISSUE THREAD

**Issue by rbf1362** [mvakili/hesabdar#1]
سلام
دستورات راه اندازی npm رو که فرموده بودید زدم .
آخرید نسخه npm هم روی سیستمم هست 
ولی خطا میده و پروژه استارت نمیشه
لطفا راهنمایی کنید

**Comment by mvakili** [comment]
سلام
لطفا جزییات بیشتری رو درمورد خطا در اختیار من بگذارید
