### ISSUE TITLE
Web API (collaboration)

### ISSUE THREAD

**Issue by moeindev** [mvakili/hesabdar#5]
آیا میتونید وب ای پی ای رو با بنده به اشتراک بذارید؟ تو فکر ساختن اپ اندروید و ای او اس متصل به این پروژه هستم( به صورت اوپن سورس)

**Comment by mvakili** [comment]
منظورت وب api روی اینترنت هستش؟

**Comment by moeindev** [comment]
بله میخوام به API این پروژه متصل کنم

**Comment by mvakili** [comment]
این پروژه رو هاست اینترنتی بالا نیومده و فقط لوکال میتونی از api استفاده کنی

**Comment by moeindev** [comment]
میدونم، آدرساشو میخواستم، خودم ران میکنم تست میکنم

**Comment by mvakili** [comment]
اگه بک اند رو اجرا کنی
میتونی همه آدرسایی که میخای رو از این آدرس ببینی
`/swagger`

یه همچین صفحه ای میاد که با جزییات میتونی چیزایی که میخای رو پیدا کنی
![image](https://user-images.githubusercontent.com/10646372/80867037-41d31100-8ca7-11ea-9d43-6dae254f1923.png)
